---
- name: install Golang
  hosts: "{{ target }}"
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
  
  roles:
    - golang

- name: install Marija
  hosts: "{{ target }}"
  remote_user: "{{ user }}"
  
  roles:
    - marija
     
