#!/bin/env bash
chown apache:apache /var/www/nextcloud/
chown -R apache:apache /var/www/nextcloud/updater/../console.php
chown -R apache:apache /var/www/nextcloud/config
chown -R apache:apache /var/www/nextcloud/updater/../ocs-provider/
chown -R apache:apache /var/www/nextcloud/updater/../ocs
chown -R apache:apache /var/www/nextcloud/updater/../remote.php
chown -R apache:apache /var/www/nextcloud/updater/../index.html
chown -R apache:apache /var/www/nextcloud/occ
chown -R apache:apache /var/www/nextcloud/3rdparty
chown -R apache:apache /var/www/nextcloud/core
chown -R apache:apache /var/www/nextcloud/lib
chown -R apache:apache /var/www/nextcloud/settings
chown -R apache:apache /var/www/nextcloud/cron.php
chown -R apache:apache /var/www/nextcloud/version.php
chown -R apache:apache /var/www/nextcloud/public.php
chown -R apache:apache /var/www/nextcloud/index.php
chown -R apache:apache /var/www/nextcloud/resources
chown -R apache:apache /var/www/nextcloud/db_structure.xml
chown -R apache:apache /var/www/nextcloud/.user.ini
chown -R apache:apache /var/www/nextcloud/updater/../AUTHORS
chown -R apache:apache /var/www/nextcloud/updater/../l10n/.
chown -R apache:apache /var/www/nextcloud/updater/../l10n/.gitignore
chown -R apache:apache /var/www/nextcloud/updater/../l10n/.tx/.
chown -R apache:apache /var/www/nextcloud/updater/../l10n/.tx/config
chown -R apache:apache /var/www/nextcloud/updater/../l10n/rm-old.sh
chown -R apache:apache /var/www/nextcloud/updater/../l10n/l10n.pl
chown -R apache:apache /var/www/nextcloud/updater/../index.php
chown -R apache:apache /var/www/nextcloud/updater/../status.php
chown -R apache:apache /var/www/nextcloud/updater/../.htaccess
chown -R apache:apache /var/www/nextcloud/updater/../robots.txt
